################################################################################
# Study Title: Mapping Malaysia’s Psychiatrist Workforce: A Cross-Sectional Study
# File Name: malaysia_psychiatrist_analysis.R
# Description: ARIMA time-series modeling/projections and geospatial map rendering.
################################################################################

# Load required packages
library(fpp2)
library(sf)
library(ggplot2)
library(dplyr)
library(labelled)

# Define working directory
data_dir <- "."

# ==============================================================================
# SECTION 1: ARIMA TIME-SERIES MODELING & WORKFORCE PROJECTIONS
# ==============================================================================

# Load annual qualification counts generated by Stata
grad_data <- read.csv(file.path(data_dir, "graduates.csv"))

# Convert to annual time-series object (1972 - 2023)
ts_grad <- ts(grad_data[, 2], start = c(1972), end = c(2023), frequency = 1)

# Diagnostic plot: Raw series
autoplot(ts_grad) +
  xlab("Year of Specialist Qualification") +
  ylab("Number of Currently Registered Psychiatrists") +
  theme_minimal()
ggsave(file.path(data_dir, "RawSeries.tiff"), dpi = 300, width = 7, height = 5, units = "in")

# Stationarity and unit root testing
ndiffs_val <- ndiffs(ts_grad)
cat("Required order of differencing (d):", ndiffs_val, "\n")

# Ljung-Box test on differenced series
box_test <- Box.test(diff(ts_grad), lag = 10, type = "Ljung-Box")
print(box_test)

# Fit auto-ARIMA model
fit_arima <- auto.arima(ts_grad, seasonal = FALSE)
summary(fit_arima)

# Residual diagnostics
checkresiduals(fit_arima)

# Generate 10-year forecasts (2024–2033)
forecast_10yr <- forecast(fit_arima, h = 10)
autoplot(forecast_10yr, include = 80) +
  xlab("Year") +
  ylab("Forecasted Annual Psychiatrist Qualifications") +
  theme_minimal()
ggsave(file.path(data_dir, "Figure5A.tiff"), dpi = 300, width = 7, height = 5, units = "in")

print("10-Year Mean Point Forecasts:")
print(forecast_10yr$mean)

# Note: Figure 5B (Attrition Scenarios) was compiled and rendered in Microsoft Excel 
# using the ARIMA point forecasts generated above. See 'Figure5B_Projections.xlsx'.

# ==============================================================================
# SECTION 2: GEOSPATIAL MAP RENDERING
# ==============================================================================

# Load shapefile administrative boundaries
shp_path <- file.path(data_dir, "mys_admin2.shp")

# ------------------------------------------------------------------------------
# 2.1 District-Level Psychiatrist Density
# ------------------------------------------------------------------------------
if (file.exists(shp_path)) {
  map_dist <- st_read(shp_path)
  psy_dist <- read.csv(file.path(data_dir, "district_map.csv"))
  
  # Join spatial boundaries with Stata density output
  joint_dist <- left_join(map_dist, psy_dist, by = "adm2_name")
  var_label(joint_dist$capita) <- "Psychiatrists per 100,000"
  
  # Render District Map
  ggplot(data = joint_dist) +
    geom_sf(aes(fill = capita), color = "white", size = 0.1) +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = "bottom",
      legend.title = element_text(size = 9)
    ) +
    labs(
      title = "Psychiatrist Density by District in Malaysia",
      fill = "Psychiatrists per 100,000"
    ) +
    scale_fill_viridis_c(option = "plasma", na.value = "grey90")
  
  ggsave(file.path(data_dir, "Figure6A.tiff"), dpi = 300, width = 7, height = 5, units = "in")
  
  # ----------------------------------------------------------------------------
  # 2.2 State-Level (Klang Valley Integrated) Psychiatrist Density
  # ----------------------------------------------------------------------------
  psy_state <- read.csv(file.path(data_dir, "state_map.csv"))
  
  # Join spatial boundaries with state density output
  joint_state <- left_join(map_dist, psy_state, by = "adm1_name")
  var_label(joint_state$capita) <- "Psychiatrists per 100,000"
  
  # Render State Map
  ggplot(data = joint_state) +
    geom_sf(aes(fill = capita), color = "white", size = 0.1) +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = "bottom",
      legend.title = element_text(size = 9)
    ) +
    labs(
      title = "Psychiatrist Density by State in Malaysia (Klang Valley Integrated)",
      fill = "Psychiatrists per 100,000"
    ) +
    scale_fill_viridis_c(option = "viridis", na.value = "grey90")
  
  ggsave(file.path(data_dir, "Figure4C.tiff"), dpi = 300, width = 7, height = 5, units = "in")
} else {
  warning("Shapefile 'mys_admin2.shp' not found in working directory. Map rendering skipped.")
}